import { Job, JOB_CODE } from '../models/job.model';
import * as Mechanic from './skill/skill-mechanic';
import * as VCommon from './skill/skill-v-common';
import * as VPirate from './skill/skill-v-pirate';

export const jobEntities: { [code in JOB_CODE]?: Job } = {
  ARCHMAGE_ICE_LIGHTNING: {
    code: 'ARCHMAGE_ICE_LIGHTNING',
    category: 'MAGE',
    mainStat: 'INT',
    name: '아크메이지(썬, 콜)',
    mastery: 0.25,
    skills: [],
    skillCores: [],
  },
  NIGHTLORD: {
    code: 'NIGHTLORD',
    category: 'ROGUE',
    mainStat: 'LUK',
    name: '나이트로드',
    mastery: 0.15,
    skills: [],
    skillCores: [],
  },
  DEMONAVENGER: {
    code: 'DEMONAVENGER',
    category: 'WARRIOR',
    mainStat: 'maxHP',
    name: '데몬어벤져',
    mastery: 0.2,
    skills: [],
    skillCores: [],
  },
  BISHOP: {
    code: 'BISHOP',
    category: 'MAGE',
    mainStat: 'INT',
    name: '비숍',
    mastery: 0.25,
    skills: [],
    skillCores: [],
  },
  MECHANIC: {
    code: 'MECHANIC',
    category: 'PIRATE',
    mainStat: 'DEX',
    name: '메카닉',
    mastery: 0.15,
    skills: [...Mechanic.skillCodes],
    skillCores: [...VCommon.skillCodes, ...VPirate.skillCodes],
  },
};

export const jobNames: { [code in JOB_CODE | 'M']: string } = {
  HERO: '히어로',
  PALADIN: '팔라딘',
  DARK_KNIGHT: '다크나이트',
  ARCHMAGE_FIRE_POISON: '아크메이지 (불, 독)',
  ARCHMAGE_ICE_LIGHTNING: '아크메이지 (썬, 콜)',
  BISHOP: '비숍',
  BOWMASTER: '보우마스터',
  MARKSMAN: '신궁',
  NIGHTLORD: '나이트로드',
  SHADOWER: '섀도어',
  DUALBLADE: '듀얼블레이드',
  VIPER: '바이퍼',
  CAPTAIN: '캡틴',
  CANNONSHOOTER: '캐논슈터',
  SOULMASTER: '소울마스터',
  MIHILE: '미하일',
  FLAMEWIZARD: '플레임위자드',
  WINDBREAKER: '윈드브레이커',
  NIGHTWALKER: '나이트워커',
  STRIKER: '스트라이커',
  ARAN: '아란',
  EVAN: '에반',
  LUMINOUS: '루미너스',
  MERCEDES: '메르세데스',
  PHANTOM: '팬텀',
  EUNWOL: '은월',
  BLASTER: '블래스터',
  DEMONSLAYER: '데몬슬레이어',
  DEMONAVENGER: '데몬어벤져',
  BATTLEMAGE: '배틀메이지',
  WILDHUNTER: '와일드헌터',
  MECHANIC: '메카닉',
  XENON: '제논',
  KAISER: '카이저',
  CADENA: '카데나',
  ANGELICBUSTER: '엔젤릭버스터',
  ZERO: '제로',
  KINESIS: '키네시스',
  ILLIUM: '일리움',
  ARK: '아크',
  M: '메이플M',
};
